### ISSUE TITLE
Unity.ServiceLocation version

### ISSUE THREAD

**Issue by simplicbe** [unitycontainer/service-location#2]
Currenty I've the following problem, if we install `Unity`, it will automatically resolve `Unity.ServiceLocation`. The problem is, that `Unity.ServiceLocation` installs version `2.1.1` but `Unity` ships `2.1.2`...

package.config:

```xml
  <package id="Unity" version="5.8.6" targetFramework="net451" />
  <package id="Unity.Abstractions" version="3.3.0" targetFramework="net451" />
  <package id="Unity.ServiceLocation" version="2.1.1" targetFramework="net451" />
```

Unity:

![image](https://user-images.githubusercontent.com/14359329/42096042-9d50b0a6-7bb4-11e8-8452-128181336bf5.png)

How it is possible, that `Unity` ships a newer version, than `Unity.ServiceLocation` exists in nuget?

**Comment by ENikS** [comment]
The best solution is to reference packages individually. 

Composite Unity package is going to be deprecated in next major version release.

**Comment by simplicbe** [comment]
Ok, thanks.
