### ISSUE TITLE
Not compatible with .NETStandard (Mono - Xamarin.Android)

### ISSUE THREAD

**Issue by Sergiojoel9877** [unitycontainer/service-location#3]
Just after upgrade from 2.1.2 to 5.9.0, compiler says that this version isn't compatible with .NetStandard

![bug](https://user-images.githubusercontent.com/14083538/51612312-8f36cf00-1ef7-11e9-8c49-d8ce11c7792f.png)

**Comment by ENikS** [comment]
Thank you for your help!

**Comment by Sergiojoel9877** [comment]
Hey no problem, keep your awesome and great work!
