### ISSUE TITLE
UWP compiled issue payload contains two or more files witg same destination path

### ISSUE THREAD

**Issue by EvaRichie** [unitycontainer/service-location#4]
### Description

Build UWP get error APPX1101 Payload contains two or more files with the same destination path 'Unity.Abstraction.pdb'

### To Reproduce

1. Create Blank UWP app.
2. Install Unity v5.10.2
3. Install Unity.ServiceLocation v5.10
4. Build the project will get the error.

**Comment by ENikS** [comment]
Instead of Unity, reference Unity.Container package

**Comment by EvaRichie** [comment]
Thanks, that work perfect.
